//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _00185511_AnimalWeightTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeightTrackerEntities : DbContext
    {
        public WeightTrackerEntities()
            : base("name=WeightTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<animal> animals { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<daily_exercise> daily_exercise { get; set; }
        public virtual DbSet<daily_log> daily_log { get; set; }
        public virtual DbSet<daily_meal> daily_meal { get; set; }
        public virtual DbSet<daily_measurement> daily_measurement { get; set; }
        public virtual DbSet<exercise> exercises { get; set; }
        public virtual DbSet<meal> meals { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<organizationType> organizationTypes { get; set; }
        public virtual DbSet<species> species { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
    }
}
